// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9Y8fiNwxjencA4PDuothwXpV34HqeVM',
    appId: '1:382355947281:web:eb6a0be2bb47cfde8796b0',
    messagingSenderId: '382355947281',
    projectId: 'fcmnotifications-49717',
    authDomain: 'fcmnotifications-49717.firebaseapp.com',
    storageBucket: 'fcmnotifications-49717.appspot.com',
    measurementId: 'G-5E5HXKHF3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ1CPFp9gj5mR6HX15xgaHiRYEmBYR76E',
    appId: '1:382355947281:android:aeaafc69f3823edd8796b0',
    messagingSenderId: '382355947281',
    projectId: 'fcmnotifications-49717',
    storageBucket: 'fcmnotifications-49717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC26yBjBv8nymH5JSoLk8NGqW2i_Qx_2Ck',
    appId: '1:382355947281:ios:297c5bb8751aed388796b0',
    messagingSenderId: '382355947281',
    projectId: 'fcmnotifications-49717',
    storageBucket: 'fcmnotifications-49717.appspot.com',
    iosBundleId: 'com.example.fcmnotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC26yBjBv8nymH5JSoLk8NGqW2i_Qx_2Ck',
    appId: '1:382355947281:ios:9bb6d5ed8a0136e98796b0',
    messagingSenderId: '382355947281',
    projectId: 'fcmnotifications-49717',
    storageBucket: 'fcmnotifications-49717.appspot.com',
    iosBundleId: 'com.example.fcmnotifications.RunnerTests',
  );
}
